[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' https: data:;
      script-src 'self' https://challenges.cloudflare.com;
      style-src 'self' 'unsafe-inline';
      frame-src 'self' https://w.soundcloud.com https://challenges.cloudflare.com https://app.netlify.com;
      connect-src 'self';
      base-uri 'self';
      form-action 'self'
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
